version: '3'

services:
  web:
    build: ./source
    depends_on:
      - db
      - cache
#    tty: true
    volumes:
      - ./source:/myapp
    environment:
      # set environment(config.py)
      - ADMIN_PASSWORD=password
      - MAIL_USERNAME=example@email.com
      - MAIL_PASSWORD=password
      - ADMIN_MAIL=example@email.com
      - QN_ACCESS_KEY=''
      - QN_SECRET_KEY=''
    ports:
      - "9001:9001"

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"

  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  proxy:
    image: nginx:1.13.12
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
