version: '3'

services:
  web:
    build: ./source
    networks:
      - frontend
      - backend
#    tty: true
    volumes:
      - ./source:/myapp
    environment:
      # set environment(config.py)
      - ADMIN_PASSWORD=password
      - MAIL_USERNAME=example@email.com
      - MAIL_PASSWORD=password
      - ADMIN_MAIL=example@email.com
      - QN_ACCESS_KEY=''
      - QN_SECRET_KEY=''
    ports:
      - "9001:9001"
    depends_on:
      - db
      - cache
    command: bash -c "./wait_for_it.sh db:3306 -- docker-entrypoint.sh"

  db:
    image: mysql:5.7
    networks:
      - backend
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"

  cache:
    image: redis:latest
    networks:
      - backend
    restart: always
    ports:
      - '6379:6379'

  proxy:
    image: nginx:1.13.12
    container_name: yublog_proxy
    networks:
      - frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./source/app/static:/usr/share/nginx/html
      - ./nginx/data:/usr/share/nginx
      - ./nginx/conf.crt:/etc/letsencrypt
    depends_on:
      - web

networks:
  frontend:
  backend:

